#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

## usage: adr list
##
## Lists the architecture decision records

function index() {
	basename "$1" | sed -e 's/-.*//' | sed -e 's/^0*//'
}

adr_dir=$("$adr_bin_dir/_adr_dir")

if [ -d $adr_dir ]
then
	records=$(find $adr_dir | grep -E "^$adr_dir/[0-9]+-[^/]*\\.md" | sort)
	for f in $records
	do
		n=$(index "$f")
		status=$(awk '
		/^## Status/,/^#/ && !/^## Status/ { 
			if (!/^(#|\s*$)/) print
		}
		' $f)
		if [[ ${status,,} =~ ([a-zA-Z]*)[[:space:]]+by[[:space:]][[]([0-9]+) ]]; then
			echo -e "\e[9m$n $f\e[0m ${BASH_REMATCH[1]^^} BY ${BASH_REMATCH[2]}"
		else
			echo "$n $f"
		fi
	done
else
    echo "The $adr_dir directory does not exist"
    exit 1
fi
